import json
import sys

#local import
sys.path.append(".")
from utils import gen_utils
from utils import agent_utils
from genai_agent.data import local_config
from genai_agent.data import response_schema

def make_calculation_rule_agent_flow(category_json, spec_id_table):
    category_json = json.dumps(category_json, indent=4)
    spec_id_table = json.dumps(spec_id_table, indent=4)
    contents = f"""You are an expert Python Backend Engineer specializing in data parsing pipelines for Analog IC Design Automation.

[CIRCUIT ARCHITECTURE]
- Circuit Type: DISO_Folded_Cascode
- Output Mode: Single-Ended Output (3-column AC data expected)

[VALID MEASUREMENT CONTRACTS DATA]
Below is the Master Database mapping for the active optimization parameters. Each ID contains the data formatting rules generated by the system planner:
{
    "15": {
        "target_id": "ugbw",
        "human_name": "Unity-Gain Bandwidth",
        "contract": {
            "sim_type": "AC",
            "csv_filename": "ac_gain.csv",
            "expected_columns": 3,
            "math_primitive_recipe": "FIND_X_AT_Y"
        }
    },
    "105": {
        "target_id": "high_freq_psrr",
        "human_name": "High-Frequency PSRR",
        "contract": {
            "sim_type": "AC",
            "csv_filename": "ac_psrr.csv",
            "expected_columns": 3,
            "math_primitive_recipe": "MIN_MAX"
        }
    }
}

[TASK]
Generate a clean, structured JSON configuration mapping that maps each integer string ID directly to its active parsing recipe. The downstream execution engine will read this layout file directly. You must output a JSON dictionary following the Pydantic schema structure provided."""    
    
    try:
        struc = agent_utils.call_agent(contents=contents, response_schema=response_schema.Struct_prepare_new_type)
        print("##make_calculation_rule_struct= ", struc)
        return struc
    except Exception as e:
        # Re-raise so upstream code can decide how to handle persistent failures.
        print(f"calculation_rule_builder: call_agent failed: {e}")
        raise